#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

BLOCKY_CONFIG_FILE="${BLOCKY_CONFIG_FILE:-/config/config.yml}";
BLOCKY_ROOT="${BLOCKY_ROOT:-$(dirname $BLOCKY_CONFIG_FILE)}";
BLOCKY_ARGS="${BLOCKY_ARGS:- --apiHost 0.0.0.0 --apiPort 4000}";

cd ${BLOCKY_ROOT} || exit 1;

usercmd \
exec \
    blocky \
    --config "${BLOCKY_CONFIG_FILE}" \
    ${BLOCKY_ARGS};
